
# This file is automatically generated, you probably don't want to edit this

coinOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "coinOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            trial = 1000,
            coins = "n=20",
            prob = 0.5,
            slika = FALSE, ...) {

            super$initialize(
                package='clt',
                name='coin',
                requiresData=FALSE,
                ...)

            private$..trial <- jmvcore::OptionInteger$new(
                "trial",
                trial,
                min=1,
                max=50000,
                default=1000)
            private$..coins <- jmvcore::OptionList$new(
                "coins",
                coins,
                options=list(
                    "n=3",
                    "n=5",
                    "n=10",
                    "n=20",
                    "n=50",
                    "n=100",
                    "n=200"),
                default="n=20")
            private$..prob <- jmvcore::OptionNumber$new(
                "prob",
                prob,
                min=0.01,
                max=0.999,
                default=0.5)
            private$..slika <- jmvcore::OptionBool$new(
                "slika",
                slika,
                default=FALSE)

            self$.addOption(private$..trial)
            self$.addOption(private$..coins)
            self$.addOption(private$..prob)
            self$.addOption(private$..slika)
        }),
    active = list(
        trial = function() private$..trial$value,
        coins = function() private$..coins$value,
        prob = function() private$..prob$value,
        slika = function() private$..slika$value),
    private = list(
        ..trial = NA,
        ..coins = NA,
        ..prob = NA,
        ..slika = NA)
)

coinResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        izpis = function() private$.items[["izpis"]],
        slika = function() private$.items[["slika"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Tossing coin")
            self$add(jmvcore::Table$new(
                options=options,
                name="izpis",
                title="Summary",
                rows=1,
                columns=list(
                    list(
                        `name`="trials", 
                        `title`="Trials", 
                        `type`="integer"),
                    list(
                        `name`="koins", 
                        `title`="Coins (n)", 
                        `type`="integer"),
                    list(
                        `name`="verjet", 
                        `title`="Probability (p)", 
                        `type`="number"),
                    list(
                        `name`="np", 
                        `title`="np", 
                        `type`="integer"),
                    list(
                        `name`="np1", 
                        `title`="n(1-p)", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="slika",
                title="Histogram",
                visible=FALSE,
                width=600,
                height=400,
                renderFun=".slika"))}))

coinBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "coinBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'clt',
                name = 'coin',
                version = c(1,0,0),
                options = options,
                results = coinResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Tossing coin
#'
#' 
#' @param trial .
#' @param coins .
#' @param prob .
#' @param slika .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$izpis} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$slika} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$izpis$asDF}
#'
#' \code{as.data.frame(results$izpis)}
#'
#' @export
coin <- function(
    trial = 1000,
    coins = "n=20",
    prob = 0.5,
    slika = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('coin requires jmvcore to be installed (restart may be required)')


    options <- coinOptions$new(
        trial = trial,
        coins = coins,
        prob = prob,
        slika = slika)

    analysis <- coinClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
