
# This file is automatically generated, you probably don't want to edit this

diceOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "diceOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            trial = 1000,
            dice = 3,
            sides = 6,
            slikak = FALSE, ...) {

            super$initialize(
                package='clt',
                name='dice',
                requiresData=FALSE,
                ...)

            private$..trial <- jmvcore::OptionInteger$new(
                "trial",
                trial,
                min=1,
                max=10000,
                default=1000)
            private$..dice <- jmvcore::OptionInteger$new(
                "dice",
                dice,
                min=1,
                max=6,
                default=3)
            private$..sides <- jmvcore::OptionInteger$new(
                "sides",
                sides,
                min=2,
                max=10,
                default=6)
            private$..slikak <- jmvcore::OptionBool$new(
                "slikak",
                slikak,
                default=FALSE)

            self$.addOption(private$..trial)
            self$.addOption(private$..dice)
            self$.addOption(private$..sides)
            self$.addOption(private$..slikak)
        }),
    active = list(
        trial = function() private$..trial$value,
        dice = function() private$..dice$value,
        sides = function() private$..sides$value,
        slikak = function() private$..slikak$value),
    private = list(
        ..trial = NA,
        ..dice = NA,
        ..sides = NA,
        ..slikak = NA)
)

diceResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        izpis = function() private$.items[["izpis"]],
        slikak = function() private$.items[["slikak"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Throwing dice")
            self$add(jmvcore::Table$new(
                options=options,
                name="izpis",
                title="Summary",
                rows=1,
                columns=list(
                    list(
                        `name`="trials", 
                        `title`="No. of trials", 
                        `type`="integer"),
                    list(
                        `name`="dic", 
                        `title`="No. of dices (n)", 
                        `type`="integer"),
                    list(
                        `name`="side", 
                        `title`="No. of sides", 
                        `type`="integer"),
                    list(
                        `name`="samplespace", 
                        `title`="Event space", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="slikak",
                title="Histogram",
                visible=FALSE,
                width=600,
                height=400,
                renderFun=".slikak"))}))

diceBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "diceBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'clt',
                name = 'dice',
                version = c(1,0,0),
                options = options,
                results = diceResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Throwing dice
#'
#' 
#' @param trial .
#' @param dice .
#' @param sides .
#' @param slikak .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$izpis} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$slikak} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$izpis$asDF}
#'
#' \code{as.data.frame(results$izpis)}
#'
#' @export
dice <- function(
    trial = 1000,
    dice = 3,
    sides = 6,
    slikak = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('dice requires jmvcore to be installed (restart may be required)')


    options <- diceOptions$new(
        trial = trial,
        dice = dice,
        sides = sides,
        slikak = slikak)

    analysis <- diceClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
