
# This file is automatically generated, you probably don't want to edit this

simhOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simhOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dif = 0,
            sam = 15,
            numer = 20,
            pval = 0.05, ...) {

            super$initialize(
                package="clt",
                name="simh",
                requiresData=FALSE,
                ...)

            private$..dif <- jmvcore::OptionInteger$new(
                "dif",
                dif,
                min=0,
                max=10,
                default=0)
            private$..sam <- jmvcore::OptionInteger$new(
                "sam",
                sam,
                min=5,
                max=500,
                default=15)
            private$..numer <- jmvcore::OptionInteger$new(
                "numer",
                numer,
                min=0,
                max=2000,
                default=20)
            private$..pval <- jmvcore::OptionNumber$new(
                "pval",
                pval,
                min=0,
                max=0.3,
                default=0.05)

            self$.addOption(private$..dif)
            self$.addOption(private$..sam)
            self$.addOption(private$..numer)
            self$.addOption(private$..pval)
        }),
    active = list(
        dif = function() private$..dif$value,
        sam = function() private$..sam$value,
        numer = function() private$..numer$value,
        pval = function() private$..pval$value),
    private = list(
        ..dif = NA,
        ..sam = NA,
        ..numer = NA,
        ..pval = NA)
)

simhResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simhResults",
    inherit = jmvcore::Group,
    active = list(
        izpis = function() private$.items[["izpis"]],
        plotci = function() private$.items[["plotci"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Testing Hypothesis")
            self$add(jmvcore::Table$new(
                options=options,
                name="izpis",
                title="Summary",
                rows=1,
                columns=list(
                    list(
                        `name`="raz", 
                        `title`="Expected diff.", 
                        `type`="integer"),
                    list(
                        `name`="dej", 
                        `title`="Average diff. in means", 
                        `type`="number"),
                    list(
                        `name`="sam", 
                        `title`="Sample size", 
                        `type`="integer"),
                    list(
                        `name`="pon", 
                        `title`="Trials", 
                        `type`="integer"),
                    list(
                        `name`="del", 
                        `title`="P of sig. tests", 
                        `type`="number"),
                    list(
                        `name`="pval", 
                        `title`="Critical p", 
                        `type`="number")),
                clearWith=list(
                    "dif",
                    "sam",
                    "numer",
                    "pval")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotci",
                title="Confidence intervals",
                width=600,
                height=400,
                renderFun=".plotci",
                clearWith=list(
                    "dif",
                    "sam",
                    "numer",
                    "pval")))}))

simhBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simhBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "clt",
                name = "simh",
                version = c(1,0,0),
                options = options,
                results = simhResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Testing Hypothesis
#'
#' 
#' @param dif .
#' @param sam .
#' @param numer .
#' @param pval .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$izpis} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotci} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$izpis$asDF}
#'
#' \code{as.data.frame(results$izpis)}
#'
#' @export
simh <- function(
    dif = 0,
    sam = 15,
    numer = 20,
    pval = 0.05) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("simh requires jmvcore to be installed (restart may be required)")


    options <- simhOptions$new(
        dif = dif,
        sam = sam,
        numer = numer,
        pval = pval)

    analysis <- simhClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

