
# This file is automatically generated, you probably don't want to edit this

simrOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "simrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            numer = 50,
            korel = 0.7,
            ci = FALSE,
            scat = FALSE, ...) {

            super$initialize(
                package='clt',
                name='simr',
                requiresData=FALSE,
                ...)

            private$..numer <- jmvcore::OptionInteger$new(
                "numer",
                numer,
                min=2,
                max=5000,
                default=50)
            private$..korel <- jmvcore::OptionNumber$new(
                "korel",
                korel,
                min=-1,
                max=1,
                default=0.7)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..scat <- jmvcore::OptionBool$new(
                "scat",
                scat,
                default=FALSE)

            self$.addOption(private$..numer)
            self$.addOption(private$..korel)
            self$.addOption(private$..ci)
            self$.addOption(private$..scat)
        }),
    active = list(
        numer = function() private$..numer$value,
        korel = function() private$..korel$value,
        ci = function() private$..ci$value,
        scat = function() private$..scat$value),
    private = list(
        ..numer = NA,
        ..korel = NA,
        ..ci = NA,
        ..scat = NA)
)

simrResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        izpis = function() private$.items[["izpis"]],
        scat = function() private$.items[["scat"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation sim")
            self$add(jmvcore::Table$new(
                options=options,
                name="izpis",
                title="Summary",
                rows=1,
                columns=list(
                    list(
                        `name`="numer", 
                        `title`="No. of pairs", 
                        `type`="integer"),
                    list(
                        `name`="kor", 
                        `title`="Correlation", 
                        `type`="number"),
                    list(
                        `name`="ciL", 
                        `title`="Lower CI (95 %)", 
                        `type`="number", 
                        `visible`="(ci)"),
                    list(
                        `name`="ciU", 
                        `title`="Upper CI (95 %)", 
                        `type`="number", 
                        `visible`="(ci)")),
                clearWith=list(
                    "numer",
                    "korel")))
            self$add(jmvcore::Image$new(
                options=options,
                name="scat",
                title="Scatterplot",
                visible=FALSE,
                width=400,
                height=400,
                renderFun=".scat",
                clearWith=list(
                    "numer",
                    "korel")))}))

simrBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "simrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'clt',
                name = 'simr',
                version = c(1,0,0),
                options = options,
                results = simrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Correlation sim
#'
#' 
#' @param numer .
#' @param korel .
#' @param ci .
#' @param scat .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$izpis} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$scat} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$izpis$asDF}
#'
#' \code{as.data.frame(results$izpis)}
#'
#' @export
simr <- function(
    numer = 50,
    korel = 0.7,
    ci = FALSE,
    scat = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('simr requires jmvcore to be installed (restart may be required)')


    options <- simrOptions$new(
        numer = numer,
        korel = korel,
        ci = ci,
        scat = scat)

    analysis <- simrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
